//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrySystem.Presentation.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndustrySystem.Presentation.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Industry System 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Data Management 的本地化字符串。
        /// </summary>
        public static string Nav_DataManagement {
            get {
                return ResourceManager.GetString("Nav_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Management 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceManagement {
            get {
                return ResourceManager.GetString("Nav_DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Device Params 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceParams {
            get {
                return ResourceManager.GetString("Nav_DeviceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experiment Config 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experiment Group Config 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experiment Group Templates 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupTemplates {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experiment History 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentHistory {
            get {
                return ResourceManager.GetString("Nav_ExperimentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Experiment Management 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentManagement {
            get {
                return ResourceManager.GetString("Nav_ExperimentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory 的本地化字符串。
        /// </summary>
        public static string Nav_Inventory {
            get {
                return ResourceManager.GetString("Nav_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Inventory Records 的本地化字符串。
        /// </summary>
        public static string Nav_InventoryRecords {
            get {
                return ResourceManager.GetString("Nav_InventoryRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Manual Debug 的本地化字符串。
        /// </summary>
        public static string Nav_ManualDebug {
            get {
                return ResourceManager.GetString("Nav_ManualDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Info 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialInfo {
            get {
                return ResourceManager.GetString("Nav_MaterialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Material Management 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialManagement {
            get {
                return ResourceManager.GetString("Nav_MaterialManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Operation Logs 的本地化字符串。
        /// </summary>
        public static string Nav_OperationLogs {
            get {
                return ResourceManager.GetString("Nav_OperationLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Peripheral Debug 的本地化字符串。
        /// </summary>
        public static string Nav_PeripheralDebug {
            get {
                return ResourceManager.GetString("Nav_PeripheralDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Permissions 的本地化字符串。
        /// </summary>
        public static string Nav_Permissions {
            get {
                return ResourceManager.GetString("Nav_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Realtime Data 的本地化字符串。
        /// </summary>
        public static string Nav_RealtimeData {
            get {
                return ResourceManager.GetString("Nav_RealtimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Roles 的本地化字符串。
        /// </summary>
        public static string Nav_Roles {
            get {
                return ResourceManager.GetString("Nav_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Dashboard 的本地化字符串。
        /// </summary>
        public static string Nav_RunDashboard {
            get {
                return ResourceManager.GetString("Nav_RunDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Run Experiment 的本地化字符串。
        /// </summary>
        public static string Nav_RunExperiment {
            get {
                return ResourceManager.GetString("Nav_RunExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Shelf Info 的本地化字符串。
        /// </summary>
        public static string Nav_ShelfInfo {
            get {
                return ResourceManager.GetString("Nav_ShelfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Management 的本地化字符串。
        /// </summary>
        public static string Nav_SystemManagement {
            get {
                return ResourceManager.GetString("Nav_SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Templates 的本地化字符串。
        /// </summary>
        public static string Nav_Templates {
            get {
                return ResourceManager.GetString("Nav_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Users 的本地化字符串。
        /// </summary>
        public static string Nav_Users {
            get {
                return ResourceManager.GetString("Nav_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Admin 的本地化字符串。
        /// </summary>
        public static string User_AdminName {
            get {
                return ResourceManager.GetString("User_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Administrator 的本地化字符串。
        /// </summary>
        public static string User_AdminRole {
            get {
                return ResourceManager.GetString("User_AdminRole", resourceCulture);
            }
        }
    }
}
