//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrySystem.Presentation.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }

        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndustrySystem.Presentation.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 暂无告警 的本地化字符串。
        /// </summary>
        public static string Alarm_NoAlarms {
            get {
                return ResourceManager.GetString("Alarm_NoAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已确认 的本地化字符串。
        /// </summary>
        public static string Alarm_Status_Acknowledged {
            get {
                return ResourceManager.GetString("Alarm_Status_Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认 的本地化字符串。
        /// </summary>
        public static string Alarm_Status_Unacknowledged {
            get {
                return ResourceManager.GetString("Alarm_Status_Unacknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工业系统 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Btn_Acknowledge {
            get {
                return ResourceManager.GetString("Btn_Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增实验组 的本地化字符串。
        /// </summary>
        public static string Btn_AddExperimentGroup {
            get {
                return ResourceManager.GetString("Btn_AddExperimentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增权限 的本地化字符串。
        /// </summary>
        public static string Btn_AddPermission {
            get {
                return ResourceManager.GetString("Btn_AddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增角色 的本地化字符串。
        /// </summary>
        public static string Btn_AddRole {
            get {
                return ResourceManager.GetString("Btn_AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增模板 的本地化字符串。
        /// </summary>
        public static string Btn_AddTemplate {
            get {
                return ResourceManager.GetString("Btn_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户 的本地化字符串。
        /// </summary>
        public static string Btn_AddUser {
            get {
                return ResourceManager.GetString("Btn_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 容器配置 的本地化字符串。
        /// </summary>
        public static string Btn_ContainerConfig {
            get {
                return ResourceManager.GetString("Btn_ContainerConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 详情 的本地化字符串。
        /// </summary>
        public static string Btn_Details {
            get {
                return ResourceManager.GetString("Btn_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Btn_First {
            get {
                return ResourceManager.GetString("Btn_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Btn_Go {
            get {
                return ResourceManager.GetString("Btn_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库 的本地化字符串。
        /// </summary>
        public static string Btn_Inbound {
            get {
                return ResourceManager.GetString("Btn_Inbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末页 的本地化字符串。
        /// </summary>
        public static string Btn_Last {
            get {
                return ResourceManager.GetString("Btn_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建模板 的本地化字符串。
        /// </summary>
        public static string Btn_NewTemplate {
            get {
                return ResourceManager.GetString("Btn_NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库 的本地化字符串。
        /// </summary>
        public static string Btn_Outbound {
            get {
                return ResourceManager.GetString("Btn_Outbound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Btn_Pause {
            get {
                return ResourceManager.GetString("Btn_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Btn_Prev {
            get {
                return ResourceManager.GetString("Btn_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Btn_Resume {
            get {
                return ResourceManager.GetString("Btn_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架配置 的本地化字符串。
        /// </summary>
        public static string Btn_ShelfConfig {
            get {
                return ResourceManager.GetString("Btn_ShelfConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Btn_Start {
            get {
                return ResourceManager.GetString("Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Btn_Stop {
            get {
                return ResourceManager.GetString("Btn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Col_Actions {
            get {
                return ResourceManager.GetString("Col_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批次数 的本地化字符串。
        /// </summary>
        public static string Col_BatchCount {
            get {
                return ResourceManager.GetString("Col_BatchCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批号 的本地化字符串。
        /// </summary>
        public static string Col_BatchNo {
            get {
                return ResourceManager.GetString("Col_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAS号 的本地化字符串。
        /// </summary>
        public static string Col_CasNo {
            get {
                return ResourceManager.GetString("Col_CasNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类别 的本地化字符串。
        /// </summary>
        public static string Col_Category {
            get {
                return ResourceManager.GetString("Col_Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Col_Common_Actions {
            get {
                return ResourceManager.GetString("Col_Common_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Col_Common_Description {
            get {
                return ResourceManager.GetString("Col_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string Col_Common_Id {
            get {
                return ResourceManager.GetString("Col_Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Col_Common_Name {
            get {
                return ResourceManager.GetString("Col_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Col_Created {
            get {
                return ResourceManager.GetString("Col_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Col_CreatedBy {
            get {
                return ResourceManager.GetString("Col_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Col_Description {
            get {
                return ResourceManager.GetString("Col_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Col_DisplayName {
            get {
                return ResourceManager.GetString("Col_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        public static string Col_EnabledStatus {
            get {
                return ResourceManager.GetString("Col_EnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期 的本地化字符串。
        /// </summary>
        public static string Col_ExpiryDate {
            get {
                return ResourceManager.GetString("Col_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string Col_Group {
            get {
                return ResourceManager.GetString("Col_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组名称 的本地化字符串。
        /// </summary>
        public static string Col_GroupName {
            get {
                return ResourceManager.GetString("Col_GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全等级 的本地化字符串。
        /// </summary>
        public static string Col_HazardLevel {
            get {
                return ResourceManager.GetString("Col_HazardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 / 安全库存 的本地化字符串。
        /// </summary>
        public static string Col_Inventory_SafetyStock {
            get {
                return ResourceManager.GetString("Col_Inventory_SafetyStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近入库 的本地化字符串。
        /// </summary>
        public static string Col_LastInboundDate {
            get {
                return ResourceManager.GetString("Col_LastInboundDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 位置 的本地化字符串。
        /// </summary>
        public static string Col_Location {
            get {
                return ResourceManager.GetString("Col_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产日期 的本地化字符串。
        /// </summary>
        public static string Col_ManufactureDate {
            get {
                return ResourceManager.GetString("Col_ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料 的本地化字符串。
        /// </summary>
        public static string Col_Material {
            get {
                return ResourceManager.GetString("Col_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料类型 的本地化字符串。
        /// </summary>
        public static string Col_MaterialType {
            get {
                return ResourceManager.GetString("Col_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分子式 的本地化字符串。
        /// </summary>
        public static string Col_MolecularFormula {
            get {
                return ResourceManager.GetString("Col_MolecularFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Col_Permission {
            get {
                return ResourceManager.GetString("Col_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限显示名 的本地化字符串。
        /// </summary>
        public static string Col_Permission_DisplayName {
            get {
                return ResourceManager.GetString("Col_Permission_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string Col_Permission_Name {
            get {
                return ResourceManager.GetString("Col_Permission_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯度 的本地化字符串。
        /// </summary>
        public static string Col_Purity {
            get {
                return ResourceManager.GetString("Col_Purity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Col_Role {
            get {
                return ResourceManager.GetString("Col_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Col_Role_Default {
            get {
                return ResourceManager.GetString("Col_Role_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Col_Role_Permissions {
            get {
                return ResourceManager.GetString("Col_Role_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Col_Status {
            get {
                return ResourceManager.GetString("Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验步骤摘要 的本地化字符串。
        /// </summary>
        public static string Col_StepSummary {
            get {
                return ResourceManager.GetString("Col_StepSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储条件 的本地化字符串。
        /// </summary>
        public static string Col_StorageCondition {
            get {
                return ResourceManager.GetString("Col_StorageCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string Col_Supplier {
            get {
                return ResourceManager.GetString("Col_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总量 的本地化字符串。
        /// </summary>
        public static string Col_TotalQuantity {
            get {
                return ResourceManager.GetString("Col_TotalQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 类型 的本地化字符串。
        /// </summary>
        public static string Col_Type {
            get {
                return ResourceManager.GetString("Col_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单位 的本地化字符串。
        /// </summary>
        public static string Col_Unit {
            get {
                return ResourceManager.GetString("Col_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Col_User_DisplayName {
            get {
                return ResourceManager.GetString("Col_User_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Col_User_IsActive {
            get {
                return ResourceManager.GetString("Col_User_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Col_User_Roles {
            get {
                return ResourceManager.GetString("Col_User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Col_User_UserName {
            get {
                return ResourceManager.GetString("Col_User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统操作记录 的本地化字符串。
        /// </summary>
        public static string Desc_OperationLogs {
            get {
                return ResourceManager.GetString("Desc_OperationLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置实验组编号、步骤和启用状态 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentGroupEdit_Subtitle {
            get {
                return ResourceManager.GetString("Dialog_ExperimentGroupEdit_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentGroupEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentGroupEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentTemplateEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentTemplateEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写物料库存批次信息 的本地化字符串。
        /// </summary>
        public static string Dialog_InventoryEdit_Subtitle {
            get {
                return ResourceManager.GetString("Dialog_InventoryEdit_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 填写物料基本信息、理化参数与安全来源 的本地化字符串。
        /// </summary>
        public static string Dialog_MaterialEdit_Subtitle {
            get {
                return ResourceManager.GetString("Dialog_MaterialEdit_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑物料 的本地化字符串。
        /// </summary>
        public static string Dialog_MaterialEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_MaterialEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_PermissionEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_PermissionEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_RoleEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_RoleEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许的容器类型（多选） 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_AllowedContainerTypes {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_AllowedContainerTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除所有限制 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_ClearAllRestrictions {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_ClearAllRestrictions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列数 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Hint_Columns {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Hint_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Hint_Description {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Hint_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Hint_Rows {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Hint_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架编码 * 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Hint_ShelfCode {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Hint_ShelfCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架名称 * 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Hint_ShelfName {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Hint_ShelfName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 槽位布局预览 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_SlotLayoutPreview {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_SlotLayoutPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提示：点击槽位切换启用/禁用状态，右键勾选允许的容器类型 的本地化字符串。
        /// </summary>
        public static string Dialog_ShelfEdit_Tip {
            get {
                return ResourceManager.GetString("Dialog_ShelfEdit_Tip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_UserEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_UserEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Field_Common_Active {
            get {
                return ResourceManager.GetString("Field_Common_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Field_Common_Description {
            get {
                return ResourceManager.GetString("Field_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Field_Common_DisplayName {
            get {
                return ResourceManager.GetString("Field_Common_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Field_Common_Name {
            get {
                return ResourceManager.GetString("Field_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Field_CreatedAt {
            get {
                return ResourceManager.GetString("Field_CreatedAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组Id 的本地化字符串。
        /// </summary>
        public static string Field_Experiment_GroupId {
            get {
                return ResourceManager.GetString("Field_Experiment_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板Id 的本地化字符串。
        /// </summary>
        public static string Field_Experiment_TemplateId {
            get {
                return ResourceManager.GetString("Field_Experiment_TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验ID 的本地化字符串。
        /// </summary>
        public static string Field_ExperimentId {
            get {
                return ResourceManager.GetString("Field_ExperimentId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验名称 的本地化字符串。
        /// </summary>
        public static string Field_ExperimentName {
            get {
                return ResourceManager.GetString("Field_ExperimentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验类型 的本地化字符串。
        /// </summary>
        public static string Field_ExperimentType {
            get {
                return ResourceManager.GetString("Field_ExperimentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否模板 的本地化字符串。
        /// </summary>
        public static string Field_IsTemplate {
            get {
                return ResourceManager.GetString("Field_IsTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 关联参数 的本地化字符串。
        /// </summary>
        public static string Field_LinkedParameter {
            get {
                return ResourceManager.GetString("Field_LinkedParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Field_Material_Qty {
            get {
                return ResourceManager.GetString("Field_Material_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Field_Role_Default {
            get {
                return ResourceManager.GetString("Field_Role_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Field_User_DisplayName {
            get {
                return ResourceManager.GetString("Field_User_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Field_User_Password {
            get {
                return ResourceManager.GetString("Field_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Field_User_UserName {
            get {
                return ResourceManager.GetString("Field_User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部级别 的本地化字符串。
        /// </summary>
        public static string Hint_AllLevels {
            get {
                return ResourceManager.GetString("Hint_AllLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部类型 的本地化字符串。
        /// </summary>
        public static string Hint_AllTypes {
            get {
                return ResourceManager.GetString("Hint_AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批号 * 的本地化字符串。
        /// </summary>
        public static string Hint_BatchNo {
            get {
                return ResourceManager.GetString("Hint_BatchNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 品牌 的本地化字符串。
        /// </summary>
        public static string Hint_Brand {
            get {
                return ResourceManager.GetString("Hint_Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 CAS号 的本地化字符串。
        /// </summary>
        public static string Hint_CasNo {
            get {
                return ResourceManager.GetString("Hint_CasNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建人 的本地化字符串。
        /// </summary>
        public static string Hint_CreatedBy {
            get {
                return ResourceManager.GetString("Hint_CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密度 的本地化字符串。
        /// </summary>
        public static string Hint_Density {
            get {
                return ResourceManager.GetString("Hint_Density", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string Hint_EndDate {
            get {
                return ResourceManager.GetString("Hint_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Hint_EnterUserName {
            get {
                return ResourceManager.GetString("Hint_EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组编号（留空自动生成，如 EG202601001） 的本地化字符串。
        /// </summary>
        public static string Hint_ExperimentGroupCode {
            get {
                return ResourceManager.GetString("Hint_ExperimentGroupCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组名称 * 的本地化字符串。
        /// </summary>
        public static string Hint_ExperimentGroupName {
            get {
                return ResourceManager.GetString("Hint_ExperimentGroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效期至 的本地化字符串。
        /// </summary>
        public static string Hint_ExpiryDate {
            get {
                return ResourceManager.GetString("Hint_ExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全称 的本地化字符串。
        /// </summary>
        public static string Hint_FullName {
            get {
                return ResourceManager.GetString("Hint_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全等级 的本地化字符串。
        /// </summary>
        public static string Hint_HazardLevel {
            get {
                return ResourceManager.GetString("Hint_HazardLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库数量 的本地化字符串。
        /// </summary>
        public static string Hint_InboundQuantity {
            get {
                return ResourceManager.GetString("Hint_InboundQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货号 的本地化字符串。
        /// </summary>
        public static string Hint_LotNumber {
            get {
                return ResourceManager.GetString("Hint_LotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生产日期 的本地化字符串。
        /// </summary>
        public static string Hint_ManufactureDate {
            get {
                return ResourceManager.GetString("Hint_ManufactureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料类别 的本地化字符串。
        /// </summary>
        public static string Hint_MaterialCategory {
            get {
                return ResourceManager.GetString("Hint_MaterialCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码 * 的本地化字符串。
        /// </summary>
        public static string Hint_MaterialCode {
            get {
                return ResourceManager.GetString("Hint_MaterialCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编码（自动填充） 的本地化字符串。
        /// </summary>
        public static string Hint_MaterialCodeAuto {
            get {
                return ResourceManager.GetString("Hint_MaterialCodeAuto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料类型 的本地化字符串。
        /// </summary>
        public static string Hint_MaterialType {
            get {
                return ResourceManager.GetString("Hint_MaterialType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分子式 的本地化字符串。
        /// </summary>
        public static string Hint_MolecularFormula {
            get {
                return ResourceManager.GetString("Hint_MolecularFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分子量 的本地化字符串。
        /// </summary>
        public static string Hint_MolecularWeight {
            get {
                return ResourceManager.GetString("Hint_MolecularWeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 * 的本地化字符串。
        /// </summary>
        public static string Hint_Name {
            get {
                return ResourceManager.GetString("Hint_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 纯度 的本地化字符串。
        /// </summary>
        public static string Hint_Purity {
            get {
                return ResourceManager.GetString("Hint_Purity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        public static string Hint_Remarks {
            get {
                return ResourceManager.GetString("Hint_Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string Hint_Role_Name {
            get {
                return ResourceManager.GetString("Hint_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全注意事项 的本地化字符串。
        /// </summary>
        public static string Hint_SafetyNotes {
            get {
                return ResourceManager.GetString("Hint_SafetyNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全库存 的本地化字符串。
        /// </summary>
        public static string Hint_SafetyStock {
            get {
                return ResourceManager.GetString("Hint_SafetyStock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索编号 / 名称 / 创建人 的本地化字符串。
        /// </summary>
        public static string Hint_Search_ExperimentGroup {
            get {
                return ResourceManager.GetString("Hint_Search_ExperimentGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索物料名称 / 编码 / 批号 / 位置... 的本地化字符串。
        /// </summary>
        public static string Hint_Search_Inventory {
            get {
                return ResourceManager.GetString("Hint_Search_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索名称 / CAS / 品牌 / 供应商... 的本地化字符串。
        /// </summary>
        public static string Hint_Search_Material {
            get {
                return ResourceManager.GetString("Hint_Search_Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择物料 * 的本地化字符串。
        /// </summary>
        public static string Hint_SelectMaterial {
            get {
                return ResourceManager.GetString("Hint_SelectMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选择货架 的本地化字符串。
        /// </summary>
        public static string Hint_SelectShelf {
            get {
                return ResourceManager.GetString("Hint_SelectShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架 的本地化字符串。
        /// </summary>
        public static string Hint_Shelf {
            get {
                return ResourceManager.GetString("Hint_Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架列 的本地化字符串。
        /// </summary>
        public static string Hint_ShelfColumn {
            get {
                return ResourceManager.GetString("Hint_ShelfColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架行 的本地化字符串。
        /// </summary>
        public static string Hint_ShelfRow {
            get {
                return ResourceManager.GetString("Hint_ShelfRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string Hint_StartDate {
            get {
                return ResourceManager.GetString("Hint_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储条件 的本地化字符串。
        /// </summary>
        public static string Hint_StorageCondition {
            get {
                return ResourceManager.GetString("Hint_StorageCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 供应商 的本地化字符串。
        /// </summary>
        public static string Hint_Supplier {
            get {
                return ResourceManager.GetString("Hint_Supplier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板描述 的本地化字符串。
        /// </summary>
        public static string Hint_Template_Description {
            get {
                return ResourceManager.GetString("Hint_Template_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板名称 的本地化字符串。
        /// </summary>
        public static string Hint_Template_Name {
            get {
                return ResourceManager.GetString("Hint_Template_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 计量单位 的本地化字符串。
        /// </summary>
        public static string Hint_Unit {
            get {
                return ResourceManager.GetString("Hint_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string Label_Columns {
            get {
                return ResourceManager.GetString("Label_Columns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前货架 的本地化字符串。
        /// </summary>
        public static string Label_CurrentShelf {
            get {
                return ResourceManager.GetString("Label_CurrentShelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用状态 的本地化字符串。
        /// </summary>
        public static string Label_EnabledStatus {
            get {
                return ResourceManager.GetString("Label_EnabledStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验步骤（多选，关联实验ID） 的本地化字符串。
        /// </summary>
        public static string Label_ExperimentSteps {
            get {
                return ResourceManager.GetString("Label_ExperimentSteps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string Label_Rows {
            get {
                return ResourceManager.GetString("Label_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇总视图 的本地化字符串。
        /// </summary>
        public static string Label_SummaryView {
            get {
                return ResourceManager.GetString("Label_SummaryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        public static string Lbl_JumpTo {
            get {
                return ResourceManager.GetString("Lbl_JumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志级别 的本地化字符串。
        /// </summary>
        public static string Lbl_LogLevel {
            get {
                return ResourceManager.GetString("Lbl_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未登录 的本地化字符串。
        /// </summary>
        public static string Lbl_NotLoggedIn {
            get {
                return ResourceManager.GetString("Lbl_NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        public static string Lbl_OperationType {
            get {
                return ResourceManager.GetString("Lbl_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        public static string Lbl_Operator {
            get {
                return ResourceManager.GetString("Lbl_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0}/{1} 页 (共 {2} 条) 的本地化字符串。
        /// </summary>
        public static string Lbl_PageInfoFormat {
            get {
                return ResourceManager.GetString("Lbl_PageInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 的本地化字符串。
        /// </summary>
        public static string Lbl_PageSize {
            get {
                return ResourceManager.GetString("Lbl_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间范围 的本地化字符串。
        /// </summary>
        public static string Lbl_TimeRange {
            get {
                return ResourceManager.GetString("Lbl_TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至 的本地化字符串。
        /// </summary>
        public static string Lbl_To {
            get {
                return ResourceManager.GetString("Lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总页数 的本地化字符串。
        /// </summary>
        public static string Lbl_TotalPages {
            get {
                return ResourceManager.GetString("Lbl_TotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总记录 的本地化字符串。
        /// </summary>
        public static string Lbl_TotalRecords {
            get {
                return ResourceManager.GetString("Lbl_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已禁用 的本地化字符串。
        /// </summary>
        public static string Legend_Disabled {
            get {
                return ResourceManager.GetString("Legend_Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 空位 的本地化字符串。
        /// </summary>
        public static string Legend_EmptySlot {
            get {
                return ResourceManager.GetString("Legend_EmptySlot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有容器 的本地化字符串。
        /// </summary>
        public static string Legend_HasContainer {
            get {
                return ResourceManager.GetString("Legend_HasContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有库存 的本地化字符串。
        /// </summary>
        public static string Legend_HasInventory {
            get {
                return ResourceManager.GetString("Legend_HasInventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string Location_Column {
            get {
                return ResourceManager.GetString("Location_Column", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string Location_Row {
            get {
                return ResourceManager.GetString("Location_Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认告警：{0} 的本地化字符串。
        /// </summary>
        public static string Log_Alarm_Acknowledge {
            get {
                return ResourceManager.GetString("Log_Alarm_Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警数据加载完成，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string Log_Alarm_LoadComplete {
            get {
                return ResourceManager.GetString("Log_Alarm_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载告警数据 的本地化字符串。
        /// </summary>
        public static string Log_Alarm_LoadStart {
            get {
                return ResourceManager.GetString("Log_Alarm_LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_AlarmViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_AlarmViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史加载完成，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentHistory_LoadComplete {
            get {
                return ResourceManager.GetString("Log_ExperimentHistory_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载实验历史 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentHistory_LoadStart {
            get {
                return ResourceManager.GetString("Log_ExperimentHistory_LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentHistoryViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_ExperimentHistoryViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除实验：{0} 的本地化字符串。
        /// </summary>
        public static string Log_Experiments_Delete {
            get {
                return ResourceManager.GetString("Log_Experiments_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验数据加载完成，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string Log_Experiments_LoadComplete {
            get {
                return ResourceManager.GetString("Log_Experiments_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载实验数据 的本地化字符串。
        /// </summary>
        public static string Log_Experiments_LoadStart {
            get {
                return ResourceManager.GetString("Log_Experiments_LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentsViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_ExperimentsViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增实验模板：{0} 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentTemplate_Add {
            get {
                return ResourceManager.GetString("Log_ExperimentTemplate_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除实验模板：{0} 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentTemplate_Delete {
            get {
                return ResourceManager.GetString("Log_ExperimentTemplate_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板加载完成，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentTemplate_LoadComplete {
            get {
                return ResourceManager.GetString("Log_ExperimentTemplate_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载实验模板 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentTemplate_LoadStart {
            get {
                return ResourceManager.GetString("Log_ExperimentTemplate_LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_ExperimentTemplateViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_ExperimentTemplateViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件连接成功 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_Connected {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件连接失败：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_ConnectFailed {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_ConnectFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在连接硬件… 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_Connecting {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件已断开连接 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_Disconnected {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正在断开硬件连接… 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_Disconnecting {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取失败：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_ReadFailed {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_ReadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取寄存器：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_Reading {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_Reading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 读取成功：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_ReadSuccess {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_ReadSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入失败：值为空 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteEmpty {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入失败：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteFailed {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入格式错误 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteFormatError {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批量写入成功，数量：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteMultiSuccess {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteMultiSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单点写入成功：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteSingleSuccess {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteSingleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入值格式错误：{0} 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebug_WriteValueFormatError {
            get {
                return ResourceManager.GetString("Log_HardwareDebug_WriteValueFormatError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 硬件调试视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_HardwareDebugViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_HardwareDebugViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 入库：{0} 的本地化字符串。
        /// </summary>
        public static string Log_Inventory_In {
            get {
                return ResourceManager.GetString("Log_Inventory_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存加载完成，共 {0} 条 的本地化字符串。
        /// </summary>
        public static string Log_Inventory_LoadComplete {
            get {
                return ResourceManager.GetString("Log_Inventory_LoadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始加载库存 的本地化字符串。
        /// </summary>
        public static string Log_Inventory_LoadStart {
            get {
                return ResourceManager.GetString("Log_Inventory_LoadStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出库：{0} 的本地化字符串。
        /// </summary>
        public static string Log_Inventory_Out {
            get {
                return ResourceManager.GetString("Log_Inventory_Out", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_InventoryViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_InventoryViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载可运行实验列表 的本地化字符串。
        /// </summary>
        public static string Log_RunExperiment_LoadExperiments {
            get {
                return ResourceManager.GetString("Log_RunExperiment_LoadExperiments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停实验 的本地化字符串。
        /// </summary>
        public static string Log_RunExperiment_Pause {
            get {
                return ResourceManager.GetString("Log_RunExperiment_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续实验 的本地化字符串。
        /// </summary>
        public static string Log_RunExperiment_Resume {
            get {
                return ResourceManager.GetString("Log_RunExperiment_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始运行实验：{0} 的本地化字符串。
        /// </summary>
        public static string Log_RunExperiment_Start {
            get {
                return ResourceManager.GetString("Log_RunExperiment_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止实验 的本地化字符串。
        /// </summary>
        public static string Log_RunExperiment_Stop {
            get {
                return ResourceManager.GetString("Log_RunExperiment_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行实验视图模型已初始化 的本地化字符串。
        /// </summary>
        public static string Log_RunExperimentViewModel_Initialized {
            get {
                return ResourceManager.GetString("Log_RunExperimentViewModel_Initialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速登录 的本地化字符串。
        /// </summary>
        public static string Login_Quick {
            get {
                return ResourceManager.GetString("Login_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住账号 的本地化字符串。
        /// </summary>
        public static string Login_Remember {
            get {
                return ResourceManager.GetString("Login_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 气体 的本地化字符串。
        /// </summary>
        public static string Material_Category_Gas {
            get {
                return ResourceManager.GetString("Material_Category_Gas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 液体 的本地化字符串。
        /// </summary>
        public static string Material_Category_Liquid {
            get {
                return ResourceManager.GetString("Material_Category_Liquid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 固体 的本地化字符串。
        /// </summary>
        public static string Material_Category_Solid {
            get {
                return ResourceManager.GetString("Material_Category_Solid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高危险 的本地化字符串。
        /// </summary>
        public static string Material_Hazard_High {
            get {
                return ResourceManager.GetString("Material_Hazard_High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 低危 的本地化字符串。
        /// </summary>
        public static string Material_Hazard_Low {
            get {
                return ResourceManager.GetString("Material_Hazard_Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中危险 的本地化字符串。
        /// </summary>
        public static string Material_Hazard_Medium {
            get {
                return ResourceManager.GetString("Material_Hazard_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无危险 的本地化字符串。
        /// </summary>
        public static string Material_Hazard_None {
            get {
                return ResourceManager.GetString("Material_Hazard_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 避光 的本地化字符串。
        /// </summary>
        public static string Material_Storage_LightProtected {
            get {
                return ResourceManager.GetString("Material_Storage_LightProtected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 冷藏 的本地化字符串。
        /// </summary>
        public static string Material_Storage_Refrigerated {
            get {
                return ResourceManager.GetString("Material_Storage_Refrigerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 常温 的本地化字符串。
        /// </summary>
        public static string Material_Storage_RoomTemperature {
            get {
                return ResourceManager.GetString("Material_Storage_RoomTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗材 的本地化字符串。
        /// </summary>
        public static string Material_Type_Consumable {
            get {
                return ResourceManager.GetString("Material_Type_Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间产物 的本地化字符串。
        /// </summary>
        public static string Material_Type_Intermediate {
            get {
                return ResourceManager.GetString("Material_Type_Intermediate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        public static string Material_Type_Other {
            get {
                return ResourceManager.GetString("Material_Type_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 产物 的本地化字符串。
        /// </summary>
        public static string Material_Type_Product {
            get {
                return ResourceManager.GetString("Material_Type_Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原料 的本地化字符串。
        /// </summary>
        public static string Material_Type_RawMaterial {
            get {
                return ResourceManager.GetString("Material_Type_RawMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string Msg_AddSuccess {
            get {
                return ResourceManager.GetString("Msg_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除默认项 的本地化字符串。
        /// </summary>
        public static string Msg_CannotDeleteDefault {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除此权限？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeletePermission {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除此角色？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认删除该实验模板？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteTemplate {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除此用户？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string Msg_DeleteSuccess {
            get {
                return ResourceManager.GetString("Msg_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Msg_LoadFailed {
            get {
                return ResourceManager.GetString("Msg_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Msg_SuccessTitle {
            get {
                return ResourceManager.GetString("Msg_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string Msg_UpdateSuccess {
            get {
                return ResourceManager.GetString("Msg_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入权限名称 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationPermissionName {
            get {
                return ResourceManager.GetString("Msg_ValidationPermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入角色名称 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationRoleName {
            get {
                return ResourceManager.GetString("Msg_ValidationRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证错误 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationTitle {
            get {
                return ResourceManager.GetString("Msg_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationUserName {
            get {
                return ResourceManager.GetString("Msg_ValidationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Msg_WarningTitle {
            get {
                return ResourceManager.GetString("Msg_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警监控 的本地化字符串。
        /// </summary>
        public static string Nav_Alarm {
            get {
                return ResourceManager.GetString("Nav_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        public static string Nav_DataManagement {
            get {
                return ResourceManager.GetString("Nav_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceManagement {
            get {
                return ResourceManager.GetString("Nav_DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备参数 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceParams {
            get {
                return ResourceManager.GetString("Nav_DeviceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验配置 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组配置 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组模板 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupTemplates {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentHistory {
            get {
                return ResourceManager.GetString("Nav_ExperimentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验管理 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentManagement {
            get {
                return ResourceManager.GetString("Nav_ExperimentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 的本地化字符串。
        /// </summary>
        public static string Nav_Inventory {
            get {
                return ResourceManager.GetString("Nav_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出入库记录 的本地化字符串。
        /// </summary>
        public static string Nav_InventoryRecords {
            get {
                return ResourceManager.GetString("Nav_InventoryRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动调试 的本地化字符串。
        /// </summary>
        public static string Nav_ManualDebug {
            get {
                return ResourceManager.GetString("Nav_ManualDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料信息 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialInfo {
            get {
                return ResourceManager.GetString("Nav_MaterialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料管理 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialManagement {
            get {
                return ResourceManager.GetString("Nav_MaterialManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作记录 的本地化字符串。
        /// </summary>
        public static string Nav_OperationLogs {
            get {
                return ResourceManager.GetString("Nav_OperationLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外设调试 的本地化字符串。
        /// </summary>
        public static string Nav_PeripheralDebug {
            get {
                return ResourceManager.GetString("Nav_PeripheralDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string Nav_Permissions {
            get {
                return ResourceManager.GetString("Nav_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时数据 的本地化字符串。
        /// </summary>
        public static string Nav_RealtimeData {
            get {
                return ResourceManager.GetString("Nav_RealtimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string Nav_Roles {
            get {
                return ResourceManager.GetString("Nav_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行看板 的本地化字符串。
        /// </summary>
        public static string Nav_RunDashboard {
            get {
                return ResourceManager.GetString("Nav_RunDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行实验 的本地化字符串。
        /// </summary>
        public static string Nav_RunExperiment {
            get {
                return ResourceManager.GetString("Nav_RunExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架信息 的本地化字符串。
        /// </summary>
        public static string Nav_ShelfInfo {
            get {
                return ResourceManager.GetString("Nav_ShelfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string Nav_SystemManagement {
            get {
                return ResourceManager.GetString("Nav_SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板 的本地化字符串。
        /// </summary>
        public static string Nav_Templates {
            get {
                return ResourceManager.GetString("Nav_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string Nav_Users {
            get {
                return ResourceManager.GetString("Nav_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验配置: 工作进行中... 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentConfig_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 维护实验组及其关联实验步骤 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentGroups_Subtitle {
            get {
                return ResourceManager.GetString("Page_ExperimentGroups_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组管理 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentGroups_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentGroups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史 (占位) 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentHistory_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料库存管理 · 入库 / 出库 / 批次追踪 的本地化字符串。
        /// </summary>
        public static string Page_Inventory_Subtitle {
            get {
                return ResourceManager.GetString("Page_Inventory_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存管理 的本地化字符串。
        /// </summary>
        public static string Page_Inventory_Title {
            get {
                return ResourceManager.GetString("Page_Inventory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Page_Login_Title {
            get {
                return ResourceManager.GetString("Page_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料信息管理 的本地化字符串。
        /// </summary>
        public static string Page_MaterialInfo_Subtitle {
            get {
                return ResourceManager.GetString("Page_MaterialInfo_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料管理 的本地化字符串。
        /// </summary>
        public static string Page_MaterialInfo_Title {
            get {
                return ResourceManager.GetString("Page_MaterialInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架槽位总览 · 点击槽位配置容器与库存 的本地化字符串。
        /// </summary>
        public static string Page_ShelfInfo_Subtitle {
            get {
                return ResourceManager.GetString("Page_ShelfInfo_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架管理 的本地化字符串。
        /// </summary>
        public static string Page_ShelfInfo_Title {
            get {
                return ResourceManager.GetString("Page_ShelfInfo_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理实验模板与参数配置 的本地化字符串。
        /// </summary>
        public static string Page_Templates_Subtitle {
            get {
                return ResourceManager.GetString("Page_Templates_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板 的本地化字符串。
        /// </summary>
        public static string Page_Templates_Title {
            get {
                return ResourceManager.GetString("Page_Templates_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (当前：) 的本地化字符串。
        /// </summary>
        public static string Run_Label_Current {
            get {
                return ResourceManager.GetString("Run_Label_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前实验： 的本地化字符串。
        /// </summary>
        public static string Run_Label_CurrentExperiment {
            get {
                return ResourceManager.GetString("Run_Label_CurrentExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度： 的本地化字符串。
        /// </summary>
        public static string Run_Label_Progress {
            get {
                return ResourceManager.GetString("Run_Label_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        public static string Run_Label_Status {
            get {
                return ResourceManager.GetString("Run_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索权限... 的本地化字符串。
        /// </summary>
        public static string Search_Permissions {
            get {
                return ResourceManager.GetString("Search_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索角色... 的本地化字符串。
        /// </summary>
        public static string Search_Roles {
            get {
                return ResourceManager.GetString("Search_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索用户... 的本地化字符串。
        /// </summary>
        public static string Search_Users {
            get {
                return ResourceManager.GetString("Search_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新权限 的本地化字符串。
        /// </summary>
        public static string Section_AddNewPermission {
            get {
                return ResourceManager.GetString("Section_AddNewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新角色 的本地化字符串。
        /// </summary>
        public static string Section_AddNewRole {
            get {
                return ResourceManager.GetString("Section_AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新用户 的本地化字符串。
        /// </summary>
        public static string Section_AddNewUser {
            get {
                return ResourceManager.GetString("Section_AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 基础信息 的本地化字符串。
        /// </summary>
        public static string Section_BasicInfo {
            get {
                return ResourceManager.GetString("Section_BasicInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日期与位置 的本地化字符串。
        /// </summary>
        public static string Section_DateAndLocation {
            get {
                return ResourceManager.GetString("Section_DateAndLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组列表 的本地化字符串。
        /// </summary>
        public static string Section_ExperimentGroupList {
            get {
                return ResourceManager.GetString("Section_ExperimentGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验参数 的本地化字符串。
        /// </summary>
        public static string Section_ExperimentParameters {
            get {
                return ResourceManager.GetString("Section_ExperimentParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存清单 的本地化字符串。
        /// </summary>
        public static string Section_InventoryList {
            get {
                return ResourceManager.GetString("Section_InventoryList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存数量 的本地化字符串。
        /// </summary>
        public static string Section_InventoryQuantity {
            get {
                return ResourceManager.GetString("Section_InventoryQuantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料信息 的本地化字符串。
        /// </summary>
        public static string Section_MaterialInfo {
            get {
                return ResourceManager.GetString("Section_MaterialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料清单 的本地化字符串。
        /// </summary>
        public static string Section_MaterialList {
            get {
                return ResourceManager.GetString("Section_MaterialList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限列表 的本地化字符串。
        /// </summary>
        public static string Section_PermissionList {
            get {
                return ResourceManager.GetString("Section_PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 理化信息 的本地化字符串。
        /// </summary>
        public static string Section_PhysicalChemicalInfo {
            get {
                return ResourceManager.GetString("Section_PhysicalChemicalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色列表 的本地化字符串。
        /// </summary>
        public static string Section_RoleList {
            get {
                return ResourceManager.GetString("Section_RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全信息 的本地化字符串。
        /// </summary>
        public static string Section_SafetyInfo {
            get {
                return ResourceManager.GetString("Section_SafetyInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 来源信息 的本地化字符串。
        /// </summary>
        public static string Section_SourceInfo {
            get {
                return ResourceManager.GetString("Section_SourceInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板信息 的本地化字符串。
        /// </summary>
        public static string Section_TemplateInfo {
            get {
                return ResourceManager.GetString("Section_TemplateInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板列表 的本地化字符串。
        /// </summary>
        public static string Section_TemplateList {
            get {
                return ResourceManager.GetString("Section_TemplateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表 的本地化字符串。
        /// </summary>
        public static string Section_UserList {
            get {
                return ResourceManager.GetString("Section_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架 的本地化字符串。
        /// </summary>
        public static string Shelf {
            get {
                return ResourceManager.GetString("Shelf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 离心瓶 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_CentrifugeBottle {
            get {
                return ResourceManager.GetString("Shelf_Container_CentrifugeBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 耗材 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_Consumable {
            get {
                return ResourceManager.GetString("Shelf_Container_Consumable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 其他 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_Other {
            get {
                return ResourceManager.GetString("Shelf_Container_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加粉筒 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_PowderCylinder {
            get {
                return ResourceManager.GetString("Shelf_Container_PowderCylinder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 试剂盒 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_ReagentKit {
            get {
                return ResourceManager.GetString("Shelf_Container_ReagentKit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取样瓶 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_SamplingBottle {
            get {
                return ResourceManager.GetString("Shelf_Container_SamplingBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 原液瓶 的本地化字符串。
        /// </summary>
        public static string Shelf_Container_StockBottle {
            get {
                return ResourceManager.GetString("Shelf_Container_StockBottle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 孔位 的本地化字符串。
        /// </summary>
        public static string Slot {
            get {
                return ResourceManager.GetString("Slot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除权限 的本地化字符串。
        /// </summary>
        public static string Tooltip_DeletePermission {
            get {
                return ResourceManager.GetString("Tooltip_DeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除角色 的本地化字符串。
        /// </summary>
        public static string Tooltip_DeleteRole {
            get {
                return ResourceManager.GetString("Tooltip_DeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Tooltip_DeleteTemplate {
            get {
                return ResourceManager.GetString("Tooltip_DeleteTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除用户 的本地化字符串。
        /// </summary>
        public static string Tooltip_DeleteUser {
            get {
                return ResourceManager.GetString("Tooltip_DeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑权限 的本地化字符串。
        /// </summary>
        public static string Tooltip_EditPermission {
            get {
                return ResourceManager.GetString("Tooltip_EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑角色 的本地化字符串。
        /// </summary>
        public static string Tooltip_EditRole {
            get {
                return ResourceManager.GetString("Tooltip_EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Tooltip_EditTemplate {
            get {
                return ResourceManager.GetString("Tooltip_EditTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑用户 的本地化字符串。
        /// </summary>
        public static string Tooltip_EditUser {
            get {
                return ResourceManager.GetString("Tooltip_EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出日志 的本地化字符串。
        /// </summary>
        public static string Tooltip_ExportLogs {
            get {
                return ResourceManager.GetString("Tooltip_ExportLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理权限 的本地化字符串。
        /// </summary>
        public static string Tooltip_ManagePermissions {
            get {
                return ResourceManager.GetString("Tooltip_ManagePermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重置密码 的本地化字符串。
        /// </summary>
        public static string Tooltip_ResetPassword {
            get {
                return ResourceManager.GetString("Tooltip_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 切换汇总视图 的本地化字符串。
        /// </summary>
        public static string Tooltip_ToggleSummaryView {
            get {
                return ResourceManager.GetString("Tooltip_ToggleSummaryView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Type_Default {
            get {
                return ResourceManager.GetString("Type_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string User_AdminName {
            get {
                return ResourceManager.GetString("User_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理员 的本地化字符串。
        /// </summary>
        public static string User_AdminRole {
            get {
                return ResourceManager.GetString("User_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理系统权限 的本地化字符串。
        /// </summary>
        public static string View_Permissions_Subtitle {
            get {
                return ResourceManager.GetString("View_Permissions_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理用户角色 的本地化字符串。
        /// </summary>
        public static string View_Roles_Subtitle {
            get {
                return ResourceManager.GetString("View_Roles_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理系统用户 的本地化字符串。
        /// </summary>
        public static string View_Users_Subtitle {
            get {
                return ResourceManager.GetString("View_Users_Subtitle", resourceCulture);
            }
        }
    }
}
