//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace IndustrySystem.Presentation.Wpf.Resources {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IndustrySystem.Presentation.Wpf.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 暂无告警 的本地化字符串。
        /// </summary>
        public static string Alarm_NoAlarms {
            get {
                return ResourceManager.GetString("Alarm_NoAlarms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已确认 的本地化字符串。
        /// </summary>
        public static string Alarm_Status_Acknowledged {
            get {
                return ResourceManager.GetString("Alarm_Status_Acknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未确认 的本地化字符串。
        /// </summary>
        public static string Alarm_Status_Unacknowledged {
            get {
                return ResourceManager.GetString("Alarm_Status_Unacknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工业系统 的本地化字符串。
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确认 的本地化字符串。
        /// </summary>
        public static string Btn_Acknowledge {
            get {
                return ResourceManager.GetString("Btn_Acknowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增 的本地化字符串。
        /// </summary>
        public static string Btn_Add {
            get {
                return ResourceManager.GetString("Btn_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增权限 的本地化字符串。
        /// </summary>
        public static string Btn_AddPermission {
            get {
                return ResourceManager.GetString("Btn_AddPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增模板 的本地化字符串。
        /// </summary>
        public static string Btn_AddTemplate {
            get {
                return ResourceManager.GetString("Btn_AddTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新增用户 的本地化字符串。
        /// </summary>
        public static string Btn_AddUser {
            get {
                return ResourceManager.GetString("Btn_AddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消 的本地化字符串。
        /// </summary>
        public static string Btn_Cancel {
            get {
                return ResourceManager.GetString("Btn_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string Btn_Delete {
            get {
                return ResourceManager.GetString("Btn_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑 的本地化字符串。
        /// </summary>
        public static string Btn_Edit {
            get {
                return ResourceManager.GetString("Btn_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 首页 的本地化字符串。
        /// </summary>
        public static string Btn_First {
            get {
                return ResourceManager.GetString("Btn_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定 的本地化字符串。
        /// </summary>
        public static string Btn_Go {
            get {
                return ResourceManager.GetString("Btn_Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 末页 的本地化字符串。
        /// </summary>
        public static string Btn_Last {
            get {
                return ResourceManager.GetString("Btn_Last", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Btn_Login {
            get {
                return ResourceManager.GetString("Btn_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string Btn_Next {
            get {
                return ResourceManager.GetString("Btn_Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂停 的本地化字符串。
        /// </summary>
        public static string Btn_Pause {
            get {
                return ResourceManager.GetString("Btn_Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上一页 的本地化字符串。
        /// </summary>
        public static string Btn_Prev {
            get {
                return ResourceManager.GetString("Btn_Prev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 刷新 的本地化字符串。
        /// </summary>
        public static string Btn_Refresh {
            get {
                return ResourceManager.GetString("Btn_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 继续 的本地化字符串。
        /// </summary>
        public static string Btn_Resume {
            get {
                return ResourceManager.GetString("Btn_Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string Btn_Save {
            get {
                return ResourceManager.GetString("Btn_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查询 的本地化字符串。
        /// </summary>
        public static string Btn_Search {
            get {
                return ResourceManager.GetString("Btn_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始 的本地化字符串。
        /// </summary>
        public static string Btn_Start {
            get {
                return ResourceManager.GetString("Btn_Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止 的本地化字符串。
        /// </summary>
        public static string Btn_Stop {
            get {
                return ResourceManager.GetString("Btn_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Col_Actions {
            get {
                return ResourceManager.GetString("Col_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作 的本地化字符串。
        /// </summary>
        public static string Col_Common_Actions {
            get {
                return ResourceManager.GetString("Col_Common_Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Col_Common_Description {
            get {
                return ResourceManager.GetString("Col_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ID 的本地化字符串。
        /// </summary>
        public static string Col_Common_Id {
            get {
                return ResourceManager.GetString("Col_Common_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Col_Common_Name {
            get {
                return ResourceManager.GetString("Col_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建时间 的本地化字符串。
        /// </summary>
        public static string Col_Created {
            get {
                return ResourceManager.GetString("Col_Created", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Col_DisplayName {
            get {
                return ResourceManager.GetString("Col_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分组 的本地化字符串。
        /// </summary>
        public static string Col_Group {
            get {
                return ResourceManager.GetString("Col_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Col_Permission {
            get {
                return ResourceManager.GetString("Col_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限显示名 的本地化字符串。
        /// </summary>
        public static string Col_Permission_DisplayName {
            get {
                return ResourceManager.GetString("Col_Permission_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限名称 的本地化字符串。
        /// </summary>
        public static string Col_Permission_Name {
            get {
                return ResourceManager.GetString("Col_Permission_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Col_Role_Default {
            get {
                return ResourceManager.GetString("Col_Role_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限 的本地化字符串。
        /// </summary>
        public static string Col_Role_Permissions {
            get {
                return ResourceManager.GetString("Col_Role_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态 的本地化字符串。
        /// </summary>
        public static string Col_Status {
            get {
                return ResourceManager.GetString("Col_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Col_User_DisplayName {
            get {
                return ResourceManager.GetString("Col_User_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Col_User_IsActive {
            get {
                return ResourceManager.GetString("Col_User_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色 的本地化字符串。
        /// </summary>
        public static string Col_User_Roles {
            get {
                return ResourceManager.GetString("Col_User_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Col_User_UserName {
            get {
                return ResourceManager.GetString("Col_User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统操作记录 的本地化字符串。
        /// </summary>
        public static string Desc_OperationLogs {
            get {
                return ResourceManager.GetString("Desc_OperationLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentGroupEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentGroupEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_ExperimentTemplateEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_ExperimentTemplateEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_MaterialEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_MaterialEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_PermissionEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_PermissionEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_RoleEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_RoleEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编辑 的本地化字符串。
        /// </summary>
        public static string Dialog_UserEdit_Title {
            get {
                return ResourceManager.GetString("Dialog_UserEdit_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Field_Common_Active {
            get {
                return ResourceManager.GetString("Field_Common_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 描述 的本地化字符串。
        /// </summary>
        public static string Field_Common_Description {
            get {
                return ResourceManager.GetString("Field_Common_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Field_Common_DisplayName {
            get {
                return ResourceManager.GetString("Field_Common_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Field_Common_Name {
            get {
                return ResourceManager.GetString("Field_Common_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组Id 的本地化字符串。
        /// </summary>
        public static string Field_Experiment_GroupId {
            get {
                return ResourceManager.GetString("Field_Experiment_GroupId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 模板Id 的本地化字符串。
        /// </summary>
        public static string Field_Experiment_TemplateId {
            get {
                return ResourceManager.GetString("Field_Experiment_TemplateId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数量 的本地化字符串。
        /// </summary>
        public static string Field_Material_Qty {
            get {
                return ResourceManager.GetString("Field_Material_Qty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Field_Role_Default {
            get {
                return ResourceManager.GetString("Field_Role_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string Field_User_DisplayName {
            get {
                return ResourceManager.GetString("Field_User_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string Field_User_Password {
            get {
                return ResourceManager.GetString("Field_User_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string Field_User_UserName {
            get {
                return ResourceManager.GetString("Field_User_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部级别 的本地化字符串。
        /// </summary>
        public static string Hint_AllLevels {
            get {
                return ResourceManager.GetString("Hint_AllLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 全部类型 的本地化字符串。
        /// </summary>
        public static string Hint_AllTypes {
            get {
                return ResourceManager.GetString("Hint_AllTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束日期 的本地化字符串。
        /// </summary>
        public static string Hint_EndDate {
            get {
                return ResourceManager.GetString("Hint_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Hint_EnterUserName {
            get {
                return ResourceManager.GetString("Hint_EnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色名称 的本地化字符串。
        /// </summary>
        public static string Hint_Role_Name {
            get {
                return ResourceManager.GetString("Hint_Role_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始日期 的本地化字符串。
        /// </summary>
        public static string Hint_StartDate {
            get {
                return ResourceManager.GetString("Hint_StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 跳转 的本地化字符串。
        /// </summary>
        public static string Lbl_JumpTo {
            get {
                return ResourceManager.GetString("Lbl_JumpTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志级别 的本地化字符串。
        /// </summary>
        public static string Lbl_LogLevel {
            get {
                return ResourceManager.GetString("Lbl_LogLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作类型 的本地化字符串。
        /// </summary>
        public static string Lbl_OperationType {
            get {
                return ResourceManager.GetString("Lbl_OperationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作员 的本地化字符串。
        /// </summary>
        public static string Lbl_Operator {
            get {
                return ResourceManager.GetString("Lbl_Operator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 第 {0}/{1} 页 (共 {2} 条) 的本地化字符串。
        /// </summary>
        public static string Lbl_PageInfoFormat {
            get {
                return ResourceManager.GetString("Lbl_PageInfoFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 每页 的本地化字符串。
        /// </summary>
        public static string Lbl_PageSize {
            get {
                return ResourceManager.GetString("Lbl_PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 时间范围 的本地化字符串。
        /// </summary>
        public static string Lbl_TimeRange {
            get {
                return ResourceManager.GetString("Lbl_TimeRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 至 的本地化字符串。
        /// </summary>
        public static string Lbl_To {
            get {
                return ResourceManager.GetString("Lbl_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总页数 的本地化字符串。
        /// </summary>
        public static string Lbl_TotalPages {
            get {
                return ResourceManager.GetString("Lbl_TotalPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 总记录 的本地化字符串。
        /// </summary>
        public static string Lbl_TotalRecords {
            get {
                return ResourceManager.GetString("Lbl_TotalRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速登录 的本地化字符串。
        /// </summary>
        public static string Login_Quick {
            get {
                return ResourceManager.GetString("Login_Quick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 记住账号 的本地化字符串。
        /// </summary>
        public static string Login_Remember {
            get {
                return ResourceManager.GetString("Login_Remember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加成功 的本地化字符串。
        /// </summary>
        public static string Msg_AddSuccess {
            get {
                return ResourceManager.GetString("Msg_AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 无法删除默认项 的本地化字符串。
        /// </summary>
        public static string Msg_CannotDeleteDefault {
            get {
                return ResourceManager.GetString("Msg_CannotDeleteDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定删除此权限？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeletePermission {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除成功 的本地化字符串。
        /// </summary>
        public static string Msg_DeleteSuccess {
            get {
                return ResourceManager.GetString("Msg_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误 的本地化字符串。
        /// </summary>
        public static string Msg_ErrorTitle {
            get {
                return ResourceManager.GetString("Msg_ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加载失败 的本地化字符串。
        /// </summary>
        public static string Msg_LoadFailed {
            get {
                return ResourceManager.GetString("Msg_LoadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功 的本地化字符串。
        /// </summary>
        public static string Msg_SuccessTitle {
            get {
                return ResourceManager.GetString("Msg_SuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 更新成功 的本地化字符串。
        /// </summary>
        public static string Msg_UpdateSuccess {
            get {
                return ResourceManager.GetString("Msg_UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入权限名称 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationPermissionName {
            get {
                return ResourceManager.GetString("Msg_ValidationPermissionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入角色名称 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationRoleName {
            get {
                return ResourceManager.GetString("Msg_ValidationRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证错误 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationTitle {
            get {
                return ResourceManager.GetString("Msg_ValidationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入用户名 的本地化字符串。
        /// </summary>
        public static string Msg_ValidationUserName {
            get {
                return ResourceManager.GetString("Msg_ValidationUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 警告 的本地化字符串。
        /// </summary>
        public static string Msg_WarningTitle {
            get {
                return ResourceManager.GetString("Msg_WarningTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 告警监控 的本地化字符串。
        /// </summary>
        public static string Nav_Alarm {
            get {
                return ResourceManager.GetString("Nav_Alarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据管理 的本地化字符串。
        /// </summary>
        public static string Nav_DataManagement {
            get {
                return ResourceManager.GetString("Nav_DataManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备管理 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceManagement {
            get {
                return ResourceManager.GetString("Nav_DeviceManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 设备参数 的本地化字符串。
        /// </summary>
        public static string Nav_DeviceParams {
            get {
                return ResourceManager.GetString("Nav_DeviceParams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验配置 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组配置 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupConfig {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupConfig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组模板 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentGroupTemplates {
            get {
                return ResourceManager.GetString("Nav_ExperimentGroupTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentHistory {
            get {
                return ResourceManager.GetString("Nav_ExperimentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验管理 的本地化字符串。
        /// </summary>
        public static string Nav_ExperimentManagement {
            get {
                return ResourceManager.GetString("Nav_ExperimentManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 的本地化字符串。
        /// </summary>
        public static string Nav_Inventory {
            get {
                return ResourceManager.GetString("Nav_Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出入库记录 的本地化字符串。
        /// </summary>
        public static string Nav_InventoryRecords {
            get {
                return ResourceManager.GetString("Nav_InventoryRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手动调试 的本地化字符串。
        /// </summary>
        public static string Nav_ManualDebug {
            get {
                return ResourceManager.GetString("Nav_ManualDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料信息 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialInfo {
            get {
                return ResourceManager.GetString("Nav_MaterialInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 物料管理 的本地化字符串。
        /// </summary>
        public static string Nav_MaterialManagement {
            get {
                return ResourceManager.GetString("Nav_MaterialManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 操作记录 的本地化字符串。
        /// </summary>
        public static string Nav_OperationLogs {
            get {
                return ResourceManager.GetString("Nav_OperationLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 外设调试 的本地化字符串。
        /// </summary>
        public static string Nav_PeripheralDebug {
            get {
                return ResourceManager.GetString("Nav_PeripheralDebug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限管理 的本地化字符串。
        /// </summary>
        public static string Nav_Permissions {
            get {
                return ResourceManager.GetString("Nav_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实时数据 的本地化字符串。
        /// </summary>
        public static string Nav_RealtimeData {
            get {
                return ResourceManager.GetString("Nav_RealtimeData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色管理 的本地化字符串。
        /// </summary>
        public static string Nav_Roles {
            get {
                return ResourceManager.GetString("Nav_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行看板 的本地化字符串。
        /// </summary>
        public static string Nav_RunDashboard {
            get {
                return ResourceManager.GetString("Nav_RunDashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 运行实验 的本地化字符串。
        /// </summary>
        public static string Nav_RunExperiment {
            get {
                return ResourceManager.GetString("Nav_RunExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 货架信息 的本地化字符串。
        /// </summary>
        public static string Nav_ShelfInfo {
            get {
                return ResourceManager.GetString("Nav_ShelfInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统管理 的本地化字符串。
        /// </summary>
        public static string Nav_SystemManagement {
            get {
                return ResourceManager.GetString("Nav_SystemManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验模板 的本地化字符串。
        /// </summary>
        public static string Nav_Templates {
            get {
                return ResourceManager.GetString("Nav_Templates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户管理 的本地化字符串。
        /// </summary>
        public static string Nav_Users {
            get {
                return ResourceManager.GetString("Nav_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验配置: 工作进行中... 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentConfig_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentConfig_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验组: 工作进行中... 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentGroups_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentGroups_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 实验历史 (占位) 的本地化字符串。
        /// </summary>
        public static string Page_ExperimentHistory_Title {
            get {
                return ResourceManager.GetString("Page_ExperimentHistory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存 (占位) 的本地化字符串。
        /// </summary>
        public static string Page_Inventory_Title {
            get {
                return ResourceManager.GetString("Page_Inventory_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Page_Login_Title {
            get {
                return ResourceManager.GetString("Page_Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 (当前：) 的本地化字符串。
        /// </summary>
        public static string Run_Label_Current {
            get {
                return ResourceManager.GetString("Run_Label_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 当前实验： 的本地化字符串。
        /// </summary>
        public static string Run_Label_CurrentExperiment {
            get {
                return ResourceManager.GetString("Run_Label_CurrentExperiment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 进度： 的本地化字符串。
        /// </summary>
        public static string Run_Label_Progress {
            get {
                return ResourceManager.GetString("Run_Label_Progress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 状态： 的本地化字符串。
        /// </summary>
        public static string Run_Label_Status {
            get {
                return ResourceManager.GetString("Run_Label_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索权限... 的本地化字符串。
        /// </summary>
        public static string Search_Permissions {
            get {
                return ResourceManager.GetString("Search_Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索角色... 的本地化字符串。
        /// </summary>
        public static string Search_Roles {
            get {
                return ResourceManager.GetString("Search_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索用户... 的本地化字符串。
        /// </summary>
        public static string Search_Users {
            get {
                return ResourceManager.GetString("Search_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新权限 的本地化字符串。
        /// </summary>
        public static string Section_AddNewPermission {
            get {
                return ResourceManager.GetString("Section_AddNewPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新角色 的本地化字符串。
        /// </summary>
        public static string Section_AddNewRole {
            get {
                return ResourceManager.GetString("Section_AddNewRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加新用户 的本地化字符串。
        /// </summary>
        public static string Section_AddNewUser {
            get {
                return ResourceManager.GetString("Section_AddNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 权限列表 的本地化字符串。
        /// </summary>
        public static string Section_PermissionList {
            get {
                return ResourceManager.GetString("Section_PermissionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 角色列表 的本地化字符串。
        /// </summary>
        public static string Section_RoleList {
            get {
                return ResourceManager.GetString("Section_RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户列表 的本地化字符串。
        /// </summary>
        public static string Section_UserList {
            get {
                return ResourceManager.GetString("Section_UserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 启用 的本地化字符串。
        /// </summary>
        public static string Status_Active {
            get {
                return ResourceManager.GetString("Status_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 禁用 的本地化字符串。
        /// </summary>
        public static string Status_Inactive {
            get {
                return ResourceManager.GetString("Status_Inactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除权限 的本地化字符串。
        /// </summary>
        public static string Tooltip_DeletePermission {
            get {
                return ResourceManager.GetString("Tooltip_DeletePermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 编辑权限 的本地化字符串。
        /// </summary>
        public static string Tooltip_EditPermission {
            get {
                return ResourceManager.GetString("Tooltip_EditPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出日志 的本地化字符串。
        /// </summary>
        public static string Tooltip_ExportLogs {
            get {
                return ResourceManager.GetString("Tooltip_ExportLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 默认 的本地化字符串。
        /// </summary>
        public static string Type_Default {
            get {
                return ResourceManager.GetString("Type_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理员 的本地化字符串。
        /// </summary>
        public static string User_AdminName {
            get {
                return ResourceManager.GetString("User_AdminName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超级管理员 的本地化字符串。
        /// </summary>
        public static string User_AdminRole {
            get {
                return ResourceManager.GetString("User_AdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理系统权限 的本地化字符串。
        /// </summary>
        public static string View_Permissions_Subtitle {
            get {
                return ResourceManager.GetString("View_Permissions_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理用户角色 的本地化字符串。
        /// </summary>
        public static string View_Roles_Subtitle {
            get {
                return ResourceManager.GetString("View_Roles_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 管理系统用户 的本地化字符串。
        /// </summary>
        public static string View_Users_Subtitle {
            get {
                return ResourceManager.GetString("View_Users_Subtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 导出 的本地化字符串。
        /// </summary>
        public static string Btn_Export {
            get {
                return ResourceManager.GetString("Btn_Export", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确认删除？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDelete {
            get {
                return ResourceManager.GetString("Msg_ConfirmDelete", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定删除此用户？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteUser {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteUser", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 确定删除此角色？ 的本地化字符串。
        /// </summary>
        public static string Msg_ConfirmDeleteRole {
            get {
                return ResourceManager.GetString("Msg_ConfirmDeleteRole", resourceCulture);
            }
        }

        /// <summary>
        ///   查找类似 未登录 的本地化字符串。
        /// </summary>
        public static string Lbl_NotLoggedIn {
            get {
                return ResourceManager.GetString("Lbl_NotLoggedIn", resourceCulture);
            }
        }

        public static string Tooltip_ResetPassword => ResourceManager.GetString("Tooltip_ResetPassword", resourceCulture);
        public static string Tooltip_EditUser => ResourceManager.GetString("Tooltip_EditUser", resourceCulture);
        public static string Tooltip_DeleteUser => ResourceManager.GetString("Tooltip_DeleteUser", resourceCulture);
        public static string Tooltip_EditRole => ResourceManager.GetString("Tooltip_EditRole", resourceCulture);
        public static string Tooltip_DeleteRole => ResourceManager.GetString("Tooltip_DeleteRole", resourceCulture);
        public static string Tooltip_ManagePermissions => ResourceManager.GetString("Tooltip_ManagePermissions", resourceCulture);
        public static string Col_Role => ResourceManager.GetString("Col_Role", resourceCulture);
        public static string Col_Type => ResourceManager.GetString("Col_Type", resourceCulture);

        public static string Log_AlarmViewModel_Initialized => ResourceManager.GetString("Log_AlarmViewModel_Initialized", resourceCulture);
        public static string Log_Alarm_LoadStart => ResourceManager.GetString("Log_Alarm_LoadStart", resourceCulture);
        public static string Log_Alarm_LoadComplete => ResourceManager.GetString("Log_Alarm_LoadComplete", resourceCulture);
        public static string Log_Alarm_Acknowledge => ResourceManager.GetString("Log_Alarm_Acknowledge", resourceCulture);

        public static string Log_ExperimentHistoryViewModel_Initialized => ResourceManager.GetString("Log_ExperimentHistoryViewModel_Initialized", resourceCulture);
        public static string Log_ExperimentHistory_LoadStart => ResourceManager.GetString("Log_ExperimentHistory_LoadStart", resourceCulture);
        public static string Log_ExperimentHistory_LoadComplete => ResourceManager.GetString("Log_ExperimentHistory_LoadComplete", resourceCulture);

        public static string Log_ExperimentTemplateViewModel_Initialized => ResourceManager.GetString("Log_ExperimentTemplateViewModel_Initialized", resourceCulture);
        public static string Log_ExperimentTemplate_LoadStart => ResourceManager.GetString("Log_ExperimentTemplate_LoadStart", resourceCulture);
        public static string Log_ExperimentTemplate_LoadComplete => ResourceManager.GetString("Log_ExperimentTemplate_LoadComplete", resourceCulture);
        public static string Log_ExperimentTemplate_Add => ResourceManager.GetString("Log_ExperimentTemplate_Add", resourceCulture);
        public static string Log_ExperimentTemplate_Delete => ResourceManager.GetString("Log_ExperimentTemplate_Delete", resourceCulture);

        public static string Log_ExperimentsViewModel_Initialized => ResourceManager.GetString("Log_ExperimentsViewModel_Initialized", resourceCulture);
        public static string Log_Experiments_LoadStart => ResourceManager.GetString("Log_Experiments_LoadStart", resourceCulture);
        public static string Log_Experiments_LoadComplete => ResourceManager.GetString("Log_Experiments_LoadComplete", resourceCulture);
        public static string Log_Experiments_Delete => ResourceManager.GetString("Log_Experiments_Delete", resourceCulture);

        public static string Log_InventoryViewModel_Initialized => ResourceManager.GetString("Log_InventoryViewModel_Initialized", resourceCulture);
        public static string Log_Inventory_LoadStart => ResourceManager.GetString("Log_Inventory_LoadStart", resourceCulture);
        public static string Log_Inventory_LoadComplete => ResourceManager.GetString("Log_Inventory_LoadComplete", resourceCulture);
        public static string Log_Inventory_In => ResourceManager.GetString("Log_Inventory_In", resourceCulture);
        public static string Log_Inventory_Out => ResourceManager.GetString("Log_Inventory_Out", resourceCulture);

        public static string Log_HardwareDebugViewModel_Initialized => ResourceManager.GetString("Log_HardwareDebugViewModel_Initialized", resourceCulture);
        public static string Log_HardwareDebug_Connecting => ResourceManager.GetString("Log_HardwareDebug_Connecting", resourceCulture);
        public static string Log_HardwareDebug_Connected => ResourceManager.GetString("Log_HardwareDebug_Connected", resourceCulture);
        public static string Log_HardwareDebug_ConnectFailed => ResourceManager.GetString("Log_HardwareDebug_ConnectFailed", resourceCulture);
        public static string Log_HardwareDebug_Disconnecting => ResourceManager.GetString("Log_HardwareDebug_Disconnecting", resourceCulture);
        public static string Log_HardwareDebug_Disconnected => ResourceManager.GetString("Log_HardwareDebug_Disconnected", resourceCulture);
        public static string Log_HardwareDebug_Reading => ResourceManager.GetString("Log_HardwareDebug_Reading", resourceCulture);
        public static string Log_HardwareDebug_ReadSuccess => ResourceManager.GetString("Log_HardwareDebug_ReadSuccess", resourceCulture);
        public static string Log_HardwareDebug_ReadFailed => ResourceManager.GetString("Log_HardwareDebug_ReadFailed", resourceCulture);
        public static string Log_HardwareDebug_WriteEmpty => ResourceManager.GetString("Log_HardwareDebug_WriteEmpty", resourceCulture);
        public static string Log_HardwareDebug_WriteSingleSuccess => ResourceManager.GetString("Log_HardwareDebug_WriteSingleSuccess", resourceCulture);
        public static string Log_HardwareDebug_WriteFormatError => ResourceManager.GetString("Log_HardwareDebug_WriteFormatError", resourceCulture);
        public static string Log_HardwareDebug_WriteValueFormatError => ResourceManager.GetString("Log_HardwareDebug_WriteValueFormatError", resourceCulture);
        public static string Log_HardwareDebug_WriteMultiSuccess => ResourceManager.GetString("Log_HardwareDebug_WriteMultiSuccess", resourceCulture);
        public static string Log_HardwareDebug_WriteFailed => ResourceManager.GetString("Log_HardwareDebug_WriteFailed", resourceCulture);

        public static string Log_RunExperimentViewModel_Initialized => ResourceManager.GetString("Log_RunExperimentViewModel_Initialized", resourceCulture);
        public static string Log_RunExperiment_Start => ResourceManager.GetString("Log_RunExperiment_Start", resourceCulture);
        public static string Log_RunExperiment_Pause => ResourceManager.GetString("Log_RunExperiment_Pause", resourceCulture);
        public static string Log_RunExperiment_Resume => ResourceManager.GetString("Log_RunExperiment_Resume", resourceCulture);
        public static string Log_RunExperiment_Stop => ResourceManager.GetString("Log_RunExperiment_Stop", resourceCulture);
        public static string Log_RunExperiment_LoadExperiments => ResourceManager.GetString("Log_RunExperiment_LoadExperiments", resourceCulture);

        public static string Btn_AddRole => ResourceManager.GetString("Btn_AddRole", resourceCulture);
        public static string Hint_Template_Name => ResourceManager.GetString("Hint_Template_Name", resourceCulture);
        public static string Hint_Template_Description => ResourceManager.GetString("Hint_Template_Description", resourceCulture);
    }
}
